[package]
name = "dedo-rust"
version = "0.1.0"
authors = ["gabipurcaru"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lazy_static = "1.3.0"
regex = "1"
queues = "1.0.0"
peg = "0.6.3"

[dev-dependencies]
pretty_assertions = "0.6.1"