[package]
name = "dedo-rust"
version = "0.1.0"
authors = ["gabipurcaru"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lazy_static = "1.3.0"
lalrpop-util = "0.17.1"
regex = "1"

[dev-dependencies]
pretty_assertions = "0.6.1"

[build-dependencies]
lalrpop = "0.17.1"