name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: lang

    steps:
    - uses: actions/checkout@v2
    - name: Nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
