name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Nightly
      run: rustup default nightly
    - name: CD
      run: cd lang
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
