name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: lang

    steps:
    - uses: actions/checkout@v2
    - name: Nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build_wasm:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: lang

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Nightly
      run: rustup default nightly
    - name: Build
      run: wasm-pack build
    - run: wasm-pack test --node
    - run: wasm-pack test --headless --chrome
    - run: wasm-pack test --headless --firefox